name: '@tjsr/gh-util-actions/pr-exists'
description: Update an npm dependency and raise a PR
author: Tim Rowe <tim@tjsr.id.au>
inputs:
  token:
    type: string
    description: 'The GitHub token to use for PR creation'
    required: true
  branchName:
    type: string
    description: 'Name of the branch to determine whether a PR exists for'
    required: true
  repository:
    type: string
    description: 'Github repository to check for PR existence in'
    required: true

runs:
  # run-name: Update ${{ inputs.dependency }} npm dependency and raise a PR
  using: 'composite'
  steps:
  - name: Set script path
    shell: bash
    run: |
      echo "SCRIPT_DIR=$GITHUB_ACTION_PATH/scripts" >> $GITHUB_ENV

  - name: Check if PR exists
    id: check-pr-exists
    shell: bash
    if: steps.get-version.outputs.hasNewVersion == 'true' && steps.get-branch.outputs.branch != ''
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
      BRANCH_NAME: "dependency/${{ inputs.dependency }}/${{ steps.get-version.outputs.version }}"
      GITHUB_REPOSITORY: ${{ inputs.externalRepo || github.repository }}
    run: . $SCRIPT_DIR/check-pr-exists.sh
