name: '@tjsr/gh-util-actions/node-common-setup'
description: Common node setup with cache for own projects
author: Tim Rowe <tim@tjsr.id.au>
inputs:
  npmVersion:
    type: string
    description: 'The npm version to install before running the action'
    default: 'latest'
    required: false
  nodeVersion:
    type: string
    description: 'The node version to install before running the action'
    required: false
    default: '20.15.1'
  scope:
    type: string
    description: 'The scope to use for the .npmrc file if it needs overriding'
    required: false
    default: '@tjsr'
  token:
    type: string
    description: 'The GitHub token to use for PR creation'
    required: false
  cacheKey:
    type: string
    description: 'The key to use for the cache'
    required: false
    default: 'node-cache'

runs:
  # run-name: Update ${{ inputs.dependency }} npm dependency and raise a PR
  using: 'composite'
  steps:

  # Setup .npmrc file to publish to GitHub Packages
  - name: "Setup .npmrc file for scope @${{ inputs.scope }}"
    uses: actions/setup-node@v4
    with:
      always-auth: true
      node-version: ${{ inputs.nodeVersion}}
      cache: 'npm'
      registry-url: 'https://npm.pkg.github.com'
      # Defaults to the user or organization that owns the workflow file
      scope: "${{ inputs.scope }}"
      token: "${{ inputs.token }}"

  - name: Install npm ${{ inputs.npmVersion || ' or skip if no version specified' }}
    if: ${{ inputs.npmVersion != '' }}
    run: npm install -g npm@${{ inputs.npmVersion }}
    shell: bash

  - name: Cache node config and node_modules
    uses: actions/cache@main
    with:
      path: |
        ~/.npmrc
        ~/node_modules
      key: ${{ inputs.cacheKey || format('node-cache-{0}', github.run_number)}}

  - name: Force-save cache
    uses: actions/cache/save@main
    with:
      key: ${{ inputs.cacheKey || format('node-cache-{0}', github.run_number)}}
