name: Verify the composite check-upgrade-pr action works
on: push

jobs:
  verify-outdated:
    permissions:
      contents: write
      pull-requests: write
      packages: read
    name: Verify the action with no version number
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
  
    - name: Run the npm-dependency-pr util action
      uses: ./npm-dependency-pr
      id: dep-pr
      with:
        dependency: 'rimraf'
        projectPath: './npm-dependency-pr/tests'
        nodeVersion: '20.15.1'
        failOnNoNewVersion: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove the created PR
      shell: bash
      if: ${{ steps.dep-pr.outputs.pullRequestNumber == '' }}
      run: echo status=failed >> "$GITHUB_OUTPUT"

    - name: Remove the created PR
      shell: bash
      if: ${{ steps.dep-pr.outputs.pullRequestNumber != '' }}
      run: echo ACTIONS_RUNNER_HOOK_JOB_COMPLETED="gh pr close -d ${{ steps.dep-pr.outputs.pullRequestNumber }}" >> "$GITHUB_ENV"
  
  verify-remote-repo:
    permissions:
      contents: write
      pull-requests: write
      packages: read
    env:
      REMOTE_PROJECT_PATH: "${{ github.workspace }}/action-npm-outdated"
      REMOTE_REPO: 'tjsr/action-npm-outdated'
      TEST_PROJECT_PATH: "${{ github.workspace }}/action-npm-outdated/tests/npm-project"
    name: Verify the action against a different repository
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        path: 'gh-util-actions'

    - name: Check out repository code for an external project's repo
      uses: actions/checkout@v4
      with:
        repository: 'tjsr/action-npm-outdated'
        ref: 'main'
        path: 'action-npm-outdated'

    - name: Run the npm-dependency-pr util action on an external repository
      uses: ./gh-util-actions/npm-dependency-pr
      id: dep-pr
      with:
        dependency: 'rimraf'
        project: 'npm-project'
        nodeVersion: '20.15.1'
        failOnNoNewVersion: true
        token: ${{ secrets.GITHUB_TOKEN }}
        projectPath: "${{ env.TEST_PROJECT_PATH }}"
        repoPath: "${{ env.REMOTE_PROJECT_PATH }}"
        externalRepo: "${{ env.REMOTE_REPO }}"
    
    - name: Remove the created PR
      shell: bash
      if: steps.dep-pr.outputs.pullRequestNumber != ''
      run: echo ACTIONS_RUNNER_HOOK_JOB_COMPLETED="gh pr close -d ${{ steps.dep-pr.outputs.pullRequestNumber }}" >> "$GITHUB_ENV"

#   verify-specified:
#     name: Verify the action when we give a version number
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v4

#   verify-branch-exists:
#     name: Verify the action when we give a version number
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v4
    
    
#   - name: Verify the action works
#       uses: tjsr/gh-util-actions@v1
#       with:
#         dependency: 'action-npm-outdated'
#         project: 'action-npm-outdated'
#         projectPath: '.'
#         failOnNoNewVersion: true  
# runs:
#   using: 'composite'
#   steps:
#   - run-name: Checkout the repo
#     run: echo "Checking out the repo"
#     id: checkout
#     shell: bash

#   - name: Check out repository code
#     uses: actions/checkout@v4
